theme: jekyll-theme-architect
Title: Jolly's Homepage
Description: Bookmark this site to keep an eye on my learning and progress. Join me in my Software Development adventure.
Permalink: https://github.com/jolly20220861/jolly20220861.github.io/blob/main/about.md/
---
Page: Week1
---
<h2>{{ page.Week1 }}</h2>
---
Page: Week2
---
<h2>{{ page.Week2 }}</h2>
---
Page: Codes
---
<h2>{{ page.Codes }}</h2>
