theme: jekyll-theme-architect
Title: Jolly's Homepage
Description: Python, Informaton Technology and everything in between, I usPython, Informaton Technology and everything in between, I used to fight response but this time, I'm embracing it all with a growth mindset. Fight, jolly! And conquer the IT world!

Permalink: https://github.com/jolly20220861/jolly20220861.github.io/blob/main/about.md/

github:
  permlink_url: https://github.com/jolly20220861/jolly20220861.github.io/blob/main/about.md/
  another_url: pythIT.html

---
Page: Week1
---
<h2>{{ page.Week1 }}</h2>
---
Page: Week2
---
<h2>{{ page.Week2 }}</h2>
---
Page: Codes
---
<h2>{{ page.Codes }}</h2>
---
Page: journals
---
<h2>{{ page.jouornals }}</h2>
