theme: jekyll-theme-architect
Title: Jolly's Homepage
Description: Bookmark this to keep an eye on my learning and progress. Join me in my Software Development journey.
Permalink: https://github.com/jolly20220861/jolly20220861.github.io/blob/main/about.md/
Permalink: https://github.com/jolly20220861/jolly20220861.github.io/blob/main/Week%201.md/
